# Generated by Django 3.2.9 on 2022-01-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_address_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=200, null=True)),
                ('id_unique_number', models.CharField(max_length=200, null=True)),
                ('photo', models.FileField(blank=True, default='default_photo.jpg', upload_to='gameon/kyc/front_path/')),
                ('photo_2', models.FileField(blank=True, default='default_photo.jpg', upload_to='gameon/kyc/front_back/')),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_kyc', to='users.profile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AddressVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=200, null=True)),
                ('photo', models.FileField(blank=True, default='default_photo.jpg', upload_to='gameon/address_verification/')),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address_verification', to='users.profile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
