# Generated by Django 3.2.9 on 2022-01-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_addressverification_userkyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressverification',
            name='status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='not_submitted', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userkyc',
            name='status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='not_submitted', max_length=100, null=True),
        ),
    ]
