# Generated by Django 3.2.9 on 2022-01-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220107_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('B', 'Billing'), ('S', 'Shipping'), ('P', 'Primary')], max_length=1, null=True),
        ),
    ]
