# Generated by Django 3.2.9 on 2022-01-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_address_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressverification',
            name='id_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addressverification',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='id_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='id_unique_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='verified_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
