# Generated by Django 3.2.9 on 2022-01-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220108_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressverification',
            name='verified_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
