# Generated by Django 3.2.9 on 2022-01-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_addressverification_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='welcome_email',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
