# Generated by Django 3.2.9 on 2022-06-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220130_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=22, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=22, max_digits=32, null=True),
        ),
    ]
