# Generated by Django 3.2.9 on 2021-11-26 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(blank=True, max_length=400, null=True)),
                ('iconImagePath', models.ImageField(blank=True, default='default_icon_pics.jpg', upload_to='gameon/rental/category/iconImagePath/')),
            ],
        ),
        migrations.CreateModel(
            name='RentalPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(blank=True, max_length=400, null=True)),
                ('iconImagePath', models.ImageField(blank=True, default='default_icon_pics.jpg', upload_to='gameon/rental/platform/iconImagePath/')),
            ],
        ),
        migrations.CreateModel(
            name='RentalGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('numberInStock', models.IntegerField(default=1)),
                ('displayImagePath', models.ImageField(blank=True, default='default_display_pics.jpg', upload_to='gameon/rental/games/displayImagePath/')),
                ('bannerImagePath', models.ImageField(blank=True, default='default_banner_pics.jpg', upload_to='gameon/rental/games/bannerImagePath/')),
                ('thumbnailImagePath', models.ImageField(blank=True, default='default_thumbnail_pics.jpg', upload_to='gameon/rental/games/thumbnailImagePath/')),
                ('dailyRentalRate', models.IntegerField(default=1000)),
                ('adminOwned', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_cat', to='rentals.rentalcat')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_platform', to='rentals.rentalplatform')),
            ],
        ),
    ]
