# Generated by Django 3.2.9 on 2021-11-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalgame',
            name='cat',
        ),
        migrations.AddField(
            model_name='rentalgame',
            name='cat',
            field=models.ManyToManyField(related_name='game_cats', to='rentals.RentalCat'),
        ),
    ]
