# Generated by Django 3.2.9 on 2021-11-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20211126_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalgame',
            name='comingSoon',
            field=models.BooleanField(default=False),
        ),
    ]
