# Generated by Django 3.2.9 on 2021-11-26 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rentalgame_comingsoon'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalGameTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trailer_file_mp4', models.FileField(blank=True, default='default_mp4_trailer.mp4', upload_to='gameon/rental/trailers/mp4/')),
                ('trailer_file_webm', models.FileField(blank=True, default='default_webm_trailer.webm', upload_to='gameon/rental/trailers/mp4/')),
                ('highlight_title', models.CharField(blank=True, max_length=400, null=True)),
                ('highlight_desc', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailer_platform', to='rentals.rentalplatform')),
            ],
        ),
    ]
