# Generated by Django 3.2.9 on 2021-11-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rentalgametrailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalgame',
            name='featured_banner',
            field=models.BooleanField(default=False),
        ),
    ]
