# Generated by Django 3.2.9 on 2021-12-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_rentalgame_featured_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalgametrailer',
            name='trailer_banner',
            field=models.ImageField(blank=True, default='default_banner_pics.jpg', upload_to='gameon/rental/trailers/bannerImagePath/'),
        ),
    ]
