# Generated by Django 3.2.9 on 2021-12-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_rentalgametrailer_trailer_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalgame',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
