# Generated by Django 3.2.9 on 2022-01-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_auto_20220109_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalqueitems',
            name='no_of_days',
            field=models.IntegerField(default=1),
        ),
    ]
