# Generated by Django 3.2.9 on 2022-01-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_rentalqueitems_no_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalgametrailer',
            name='trailer_yt_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
