# Generated by Django 3.2.9 on 2022-07-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_rentalque_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalgame',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_platform', to='rentals.rentalplatform'),
        ),
    ]
