# Generated by Django 3.2.9 on 2022-07-16 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_alter_rentalgame_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalgametrailer',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailer_platform', to='rentals.rentalplatform'),
        ),
    ]
