# Generated by Django 3.2.9 on 2021-12-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_applogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
